-- Migration 0001 — initial schema.
--
-- Per rules.md §2.3:
--   * every table has id, created_at, updated_at
--   * every foreign key is indexed
--   * every column used in WHERE / ORDER BY is indexed
--   * snake_case names
--
-- ID strategy: TEXT primary keys holding UUID v4 strings. Generated by the
-- application layer (uuid::Uuid::new_v4()), not SQLite. Trades ~36 bytes per
-- row for cross-device portability + safer logs (no integer leakage).
--
-- Timestamps stored as TEXT in RFC 3339 form. SQLite has no native TIMESTAMP
-- type; TEXT in ISO-8601 sorts lexicographically and round-trips through
-- chrono::DateTime<Utc>.
--
-- Embedding storage: code_chunks.embedding is BLOB holding a packed f32[]
-- vector. The sqlite-vec virtual-table mirror (`code_chunks_vec`) is
-- introduced in a Phase 3 migration once sqlite-vec auto_extension wiring
-- is verified empirically — see db/mod.rs for the loader plan.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- users — desktop is single-user today; table exists for future hosted variant
-- and to scope per-user provider configs even on local installs.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id           TEXT PRIMARY KEY NOT NULL,
    email        TEXT NOT NULL UNIQUE,
    name         TEXT,
    plan         TEXT NOT NULL DEFAULT 'local',
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL
);

CREATE INDEX idx_users_email ON users(email);

-- Seed the implicit local user so foreign keys resolve on a fresh install.
-- The application replaces this row when real auth lands (Student 3 scope).
INSERT INTO users (id, email, name, plan, created_at, updated_at)
VALUES (
    '00000000-0000-4000-8000-000000000001',
    'local@testing-ide.local',
    'Local User',
    'local',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
);

-- ---------------------------------------------------------------------------
-- projects — uploaded code projects analyzed by the IDE.
-- ---------------------------------------------------------------------------
CREATE TABLE projects (
    id                  TEXT PRIMARY KEY NOT NULL,
    user_id             TEXT NOT NULL,
    name                TEXT NOT NULL,
    root_path           TEXT NOT NULL,
    file_count          INTEGER NOT NULL DEFAULT 0,
    total_size_bytes    INTEGER NOT NULL DEFAULT 0,
    status              TEXT NOT NULL DEFAULT 'pending',
    language_breakdown  TEXT NOT NULL DEFAULT '{}',
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_projects_user_id ON projects(user_id);
CREATE INDEX idx_projects_status ON projects(status);
CREATE INDEX idx_projects_created_at ON projects(created_at);

-- ---------------------------------------------------------------------------
-- project_files — every source / config / docs file discovered in a project.
-- ---------------------------------------------------------------------------
CREATE TABLE project_files (
    id           TEXT PRIMARY KEY NOT NULL,
    project_id   TEXT NOT NULL,
    path         TEXT NOT NULL,
    language     TEXT,
    size_bytes   INTEGER NOT NULL,
    file_type    TEXT NOT NULL,
    sha256       TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    UNIQUE (project_id, path)
);

CREATE INDEX idx_project_files_project_id ON project_files(project_id);
CREATE INDEX idx_project_files_language ON project_files(language);
CREATE INDEX idx_project_files_file_type ON project_files(file_type);
CREATE INDEX idx_project_files_sha256 ON project_files(sha256);

-- ---------------------------------------------------------------------------
-- ast_analyses — tree-sitter output per file (functions/classes/imports).
-- Stored as JSON text to keep the schema flexible while the parser evolves.
-- ---------------------------------------------------------------------------
CREATE TABLE ast_analyses (
    id           TEXT PRIMARY KEY NOT NULL,
    file_id      TEXT NOT NULL UNIQUE,
    functions    TEXT NOT NULL DEFAULT '[]',
    classes      TEXT NOT NULL DEFAULT '[]',
    imports      TEXT NOT NULL DEFAULT '[]',
    exports      TEXT NOT NULL DEFAULT '[]',
    parser_version TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    FOREIGN KEY (file_id) REFERENCES project_files(id) ON DELETE CASCADE
);

CREATE INDEX idx_ast_analyses_file_id ON ast_analyses(file_id);

-- ---------------------------------------------------------------------------
-- code_chunks — semantic chunks (function / class / module) with embeddings.
--
-- embedding is a packed f32 vector serialized to BLOB (little-endian).
-- Vectors are NOT compared across providers / dimensions — embedding_dim
-- and embedding_provider columns let callers filter the search set so
-- mismatched vectors never enter the same cosine sweep. See ADR-0001 for
-- the brute-force-cosine + dim-filter design and the trigger conditions
-- for migrating to a sqlite-vec vec0 mirror.
-- ---------------------------------------------------------------------------
CREATE TABLE code_chunks (
    id                 TEXT PRIMARY KEY NOT NULL,
    project_id         TEXT NOT NULL,
    file_id            TEXT NOT NULL,
    chunk_type         TEXT NOT NULL,
    name               TEXT,
    content            TEXT NOT NULL,
    start_line         INTEGER NOT NULL,
    end_line           INTEGER NOT NULL,
    token_count        INTEGER NOT NULL,
    embedding          BLOB,
    embedding_dim      INTEGER,
    embedding_provider TEXT,
    embedding_model    TEXT,
    metadata           TEXT NOT NULL DEFAULT '{}',
    created_at         TEXT NOT NULL,
    updated_at         TEXT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES project_files(id) ON DELETE CASCADE,
    -- All four embedding fields move together. Either embedding is NULL
    -- (chunk not yet indexed) or all four producer-tracking fields are
    -- populated. Enforced via CHECK so partial writes fail loudly per
    -- rules.md §1.7.
    CHECK (
        (embedding IS NULL
            AND embedding_dim IS NULL
            AND embedding_provider IS NULL
            AND embedding_model IS NULL)
        OR
        (embedding IS NOT NULL
            AND embedding_dim IS NOT NULL
            AND embedding_provider IS NOT NULL
            AND embedding_model IS NOT NULL)
    )
);

CREATE INDEX idx_code_chunks_project_id ON code_chunks(project_id);
CREATE INDEX idx_code_chunks_file_id ON code_chunks(file_id);
CREATE INDEX idx_code_chunks_chunk_type ON code_chunks(chunk_type);
-- Composite index drives RAG vector search: scope to project, then to a
-- single (provider, dim) so brute-force cosine never crosses dimensions.
CREATE INDEX idx_code_chunks_search_scope
    ON code_chunks(project_id, embedding_provider, embedding_dim);

-- ---------------------------------------------------------------------------
-- artifacts — generated test plans / cases / defect reports / etc.
-- Versioned per artifact_type within a project so regenerations preserve
-- history rather than overwrite.
-- ---------------------------------------------------------------------------
CREATE TABLE artifacts (
    id              TEXT PRIMARY KEY NOT NULL,
    project_id      TEXT NOT NULL,
    artifact_type   TEXT NOT NULL,
    title           TEXT NOT NULL,
    content_md      TEXT NOT NULL,
    structured_data TEXT NOT NULL DEFAULT '{}',
    status          TEXT NOT NULL DEFAULT 'draft',
    version         INTEGER NOT NULL DEFAULT 1,
    parent_id       TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES artifacts(id) ON DELETE SET NULL
);

CREATE INDEX idx_artifacts_project_id ON artifacts(project_id);
CREATE INDEX idx_artifacts_artifact_type ON artifacts(artifact_type);
CREATE INDEX idx_artifacts_status ON artifacts(status);
CREATE INDEX idx_artifacts_parent_id ON artifacts(parent_id);

-- ---------------------------------------------------------------------------
-- user_provider_configs — per-user LLM provider settings.
-- api_key_encrypted holds AES-GCM ciphertext (rules.md §9 + Phase 6 task).
-- ---------------------------------------------------------------------------
CREATE TABLE user_provider_configs (
    id                 TEXT PRIMARY KEY NOT NULL,
    user_id            TEXT NOT NULL,
    provider           TEXT NOT NULL,
    api_key_encrypted  BLOB,
    api_key_nonce      BLOB,
    base_url           TEXT,
    default_model      TEXT,
    is_active          INTEGER NOT NULL DEFAULT 0,
    created_at         TEXT NOT NULL,
    updated_at         TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, provider)
);

CREATE INDEX idx_user_provider_configs_user_id ON user_provider_configs(user_id);
CREATE INDEX idx_user_provider_configs_is_active ON user_provider_configs(is_active);

-- ---------------------------------------------------------------------------
-- dependencies — symbolic dependency edges between code chunks. Used by the
-- Phase 5 generator to walk the call graph during RAG retrieval.
-- Self-referential: source_chunk_id depends on target_chunk_id.
-- ---------------------------------------------------------------------------
CREATE TABLE dependencies (
    id                TEXT PRIMARY KEY NOT NULL,
    project_id        TEXT NOT NULL,
    source_chunk_id   TEXT NOT NULL,
    target_chunk_id   TEXT NOT NULL,
    dependency_type   TEXT NOT NULL,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (source_chunk_id) REFERENCES code_chunks(id) ON DELETE CASCADE,
    FOREIGN KEY (target_chunk_id) REFERENCES code_chunks(id) ON DELETE CASCADE,
    UNIQUE (source_chunk_id, target_chunk_id, dependency_type)
);

CREATE INDEX idx_dependencies_project_id ON dependencies(project_id);
CREATE INDEX idx_dependencies_source_chunk_id ON dependencies(source_chunk_id);
CREATE INDEX idx_dependencies_target_chunk_id ON dependencies(target_chunk_id);
CREATE INDEX idx_dependencies_dependency_type ON dependencies(dependency_type);
