-- Migration 0004 — sandboxed test-runner tables.
--
-- Backs the closed-loop test runner (plan/SANDBOX_TEST_RUNNER.md §5).
-- A run executes a generated test-case artifact inside a local Docker
-- sandbox; we persist the run header, one row per executed assertion,
-- and per-source-line coverage so the editor can paint gutters.
--
-- Follows rules.md §2.3 conventions established in 0001_init.sql:
--   * every table has id, created_at, updated_at (TEXT RFC-3339)
--   * TEXT UUID primary keys generated by the application layer
--   * every foreign key is indexed
--   * every column used in WHERE / ORDER BY is indexed
--   * snake_case names; parameterized SQL only at the call site
--
-- Status strings mirror the Rust `RunStatus` / `TestStatus` serde enums
-- in providers/runners/mod.rs (snake_case → single-word lowercase) and
-- the Zod literals in packages/shared/src/schemas/test-run.schema.ts.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- test_runs — one row per sandboxed execution of a test-case artifact.
-- ---------------------------------------------------------------------------
CREATE TABLE test_runs (
    id             TEXT PRIMARY KEY NOT NULL,
    artifact_id    TEXT NOT NULL,
    project_id     TEXT NOT NULL,
    -- pending | running | passed | failed | error | cancelled
    status         TEXT NOT NULL DEFAULT 'pending',
    -- runner identifier, e.g. 'docker-js'
    runner         TEXT NOT NULL,
    started_at     TEXT,
    finished_at    TEXT,
    duration_ms    INTEGER,
    passed_count   INTEGER NOT NULL DEFAULT 0,
    failed_count   INTEGER NOT NULL DEFAULT 0,
    error_message  TEXT,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_test_runs_artifact_id ON test_runs(artifact_id);
CREATE INDEX idx_test_runs_project_id ON test_runs(project_id);
CREATE INDEX idx_test_runs_status ON test_runs(status);
CREATE INDEX idx_test_runs_created_at ON test_runs(created_at);

-- ---------------------------------------------------------------------------
-- test_run_cases — one row per individual executed assertion in a run.
-- ---------------------------------------------------------------------------
CREATE TABLE test_run_cases (
    id               TEXT PRIMARY KEY NOT NULL,
    run_id           TEXT NOT NULL,
    name             TEXT NOT NULL,
    -- passed | failed | skipped
    status           TEXT NOT NULL,
    duration_ms      INTEGER NOT NULL DEFAULT 0,
    failure_message  TEXT,
    source_line      INTEGER,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL,
    FOREIGN KEY (run_id) REFERENCES test_runs(id) ON DELETE CASCADE
);

CREATE INDEX idx_test_run_cases_run_id ON test_run_cases(run_id);

-- ---------------------------------------------------------------------------
-- test_run_coverage — per-source-line hit counts for a run. A row with
-- hits = 0 marks an uncovered line.
-- ---------------------------------------------------------------------------
CREATE TABLE test_run_coverage (
    id          TEXT PRIMARY KEY NOT NULL,
    run_id      TEXT NOT NULL,
    file_path   TEXT NOT NULL,
    line        INTEGER NOT NULL,
    hits        INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    FOREIGN KEY (run_id) REFERENCES test_runs(id) ON DELETE CASCADE
);

CREATE INDEX idx_test_run_coverage_run_id_file ON test_run_coverage(run_id, file_path);
