-- Migration 0008 — persisted flaky-check history.
--
-- Backs the "persisted flaky history" phase of flaky-test detection
-- (plan/versions/v2/v2-feature-docs/FLAKY_TEST_DETECTION.md §7). A flaky
-- check runs the suite N times and classifies each test; until now the
-- aggregate verdict lived only in memory. These tables persist one row per
-- completed check plus one row per test verdict, so the UI can show how a
-- suite's flakiness trends across repeated checks.
--
-- Additive only — no existing table is altered or dropped, so the migration
-- is fully backward compatible with the v1 run-history tables (migration
-- 0004) and never touches data already on disk.
--
-- Follows rules.md §2.3 conventions established in 0001_init.sql / 0004:
--   * every table has id, created_at, updated_at (TEXT RFC-3339)
--   * TEXT UUID primary keys generated by the application layer
--   * every foreign key is indexed
--   * every column used in WHERE / ORDER BY is indexed
--   * snake_case names; parameterized SQL only at the call site
--
-- Verdict strings mirror the Rust `TestVerdict` serde enum in
-- providers/runners/mod.rs (stable_pass | stable_fail | flaky) and the Zod
-- literals in packages/shared/src/schemas/test-run.schema.ts.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- flaky_checks — one row per completed flaky check (N runs of one suite).
--
-- run_id references the iteration-#1 test_runs row persisted by the same
-- check. It is nullable + ON DELETE SET NULL so purging that single run row
-- (or it cascading away with the artifact's run history) never deletes the
-- historical check: flakiness history is meant to outlive any one run. The
-- artifact / project foreign keys still cascade, so deleting the artifact
-- removes its whole flaky history.
-- ---------------------------------------------------------------------------
CREATE TABLE flaky_checks (
    id               TEXT PRIMARY KEY NOT NULL,
    artifact_id      TEXT NOT NULL,
    project_id       TEXT NOT NULL,
    run_id           TEXT,
    total_runs       INTEGER NOT NULL,
    flaky_count      INTEGER NOT NULL DEFAULT 0,
    non_flaky_count  INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL,
    FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (run_id) REFERENCES test_runs(id) ON DELETE SET NULL
);

CREATE INDEX idx_flaky_checks_artifact_id ON flaky_checks(artifact_id);
CREATE INDEX idx_flaky_checks_project_id ON flaky_checks(project_id);
CREATE INDEX idx_flaky_checks_created_at ON flaky_checks(created_at);

-- ---------------------------------------------------------------------------
-- flaky_check_tests — one row per test verdict within a check. Mirrors the
-- in-memory FlakyTestResult so a persisted check re-renders with the same
-- per-test UI as a live one. A row with sample_failure = NULL is a test that
-- never failed across the N runs.
-- ---------------------------------------------------------------------------
CREATE TABLE flaky_check_tests (
    id               TEXT PRIMARY KEY NOT NULL,
    check_id         TEXT NOT NULL,
    name             TEXT NOT NULL,
    -- stable_pass | stable_fail | flaky
    verdict          TEXT NOT NULL,
    pass_count       INTEGER NOT NULL DEFAULT 0,
    executed_count   INTEGER NOT NULL DEFAULT 0,
    total_runs       INTEGER NOT NULL,
    sample_failure   TEXT,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL,
    FOREIGN KEY (check_id) REFERENCES flaky_checks(id) ON DELETE CASCADE
);

CREATE INDEX idx_flaky_check_tests_check_id ON flaky_check_tests(check_id);
