-- Migration 0009 — persisted mutation-score history.
--
-- Backs the "persisted history" half of Stage 1 mutation testing
-- (plan/versions/v2/v2-feature-docs/MUTATION_TESTING.md §5.5). A mutation
-- check mutates covered source lines, reruns the suite per mutant, and scores
-- killed / survived. Until now that score lived only in memory; these tables
-- persist one row per completed score plus one row per mutant, so the UI can
-- trend a suite's mutation score across repeated checks (the "Mutation
-- history" panel, mirroring the flaky trend).
--
-- Additive only — no existing table is altered or dropped, so the migration is
-- fully backward compatible with the run-history (0004) and flaky-history
-- (0008) tables and never touches data already on disk.
--
-- Mirrors 0008_flaky_checks.sql exactly (rules.md §2.3):
--   * every table has id, created_at, updated_at (TEXT RFC-3339)
--   * TEXT UUID primary keys generated by the application layer
--   * every foreign key is indexed
--   * every column used in WHERE / ORDER BY is indexed
--   * snake_case names; parameterized SQL only at the call site
--
-- Status strings mirror the Rust `MutantStatus` serde enum in
-- providers/runners/mutation.rs (killed | survived | errored) and the Zod
-- literals in packages/shared/src/schemas/mutation.schema.ts.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- mutation_checks — one row per completed mutation score.
--
-- baseline_run_id references the green baseline test_runs row this score was
-- measured against (its coverage gated which lines were mutated). It is
-- nullable + ON DELETE SET NULL so purging that run (or it cascading away with
-- the artifact's run history) never deletes the historical check: mutation
-- history is meant to outlive any one run, exactly as flaky history does. The
-- artifact / project foreign keys still cascade, so deleting the artifact
-- removes its whole mutation history.
--
-- `score` is the killed/(killed+survived) ratio in [0, 1]; the counts are kept
-- alongside so the UI need not recompute, and `total = killed+survived+errored`.
-- ---------------------------------------------------------------------------
CREATE TABLE mutation_checks (
    id               TEXT PRIMARY KEY NOT NULL,
    artifact_id      TEXT NOT NULL,
    project_id       TEXT NOT NULL,
    baseline_run_id  TEXT,
    score            REAL NOT NULL DEFAULT 0,
    killed           INTEGER NOT NULL DEFAULT 0,
    survived         INTEGER NOT NULL DEFAULT 0,
    errored          INTEGER NOT NULL DEFAULT 0,
    total            INTEGER NOT NULL DEFAULT 0,
    dropped_count    INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL,
    FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (baseline_run_id) REFERENCES test_runs(id) ON DELETE SET NULL
);

CREATE INDEX idx_mutation_checks_artifact_id ON mutation_checks(artifact_id);
CREATE INDEX idx_mutation_checks_project_id ON mutation_checks(project_id);
CREATE INDEX idx_mutation_checks_created_at ON mutation_checks(created_at);

-- ---------------------------------------------------------------------------
-- mutation_check_mutants — one row per mutant within a check. Mirrors the
-- in-memory MutantResult so a persisted check re-renders the survivor list
-- with the same per-mutant UI as a live one (file:line  original → replacement,
-- with the verdict). A row's status is killed | survived | errored.
-- ---------------------------------------------------------------------------
CREATE TABLE mutation_check_mutants (
    id               TEXT PRIMARY KEY NOT NULL,
    check_id         TEXT NOT NULL,
    file             TEXT NOT NULL,
    line             INTEGER NOT NULL,
    operator_id      TEXT NOT NULL,
    original         TEXT NOT NULL,
    replacement      TEXT NOT NULL,
    -- killed | survived | errored
    status           TEXT NOT NULL,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL,
    FOREIGN KEY (check_id) REFERENCES mutation_checks(id) ON DELETE CASCADE
);

CREATE INDEX idx_mutation_check_mutants_check_id ON mutation_check_mutants(check_id);
