-- Migration 0010 — persisted self-heal history.
--
-- Backs the "Heal history" parity item of the v2 quality-loop hardening doc
-- (plan/versions/v2/v2-feature-docs/V2_HARDENING.md §5.1). The self-healing
-- loop (SELF_HEALING_LOOP.md) runs a suite, regenerates failing tests, and
-- reruns until green / exhausted; until now its outcome lived only in memory.
-- Self-heal was the one quality axis with no persisted trail (flaky has 0008,
-- mutation has 0009). These tables persist one row per completed heal plus one
-- row per test involved in it, so the UI can trend "this suite has needed
-- healing 4 of the last 6 generations" and which tests keep regressing.
--
-- Additive only — no existing table is altered or dropped, so the migration is
-- fully backward compatible with the run-history (0004), flaky-history (0008)
-- and mutation-history (0009) tables and never touches data already on disk.
--
-- Mirrors 0008_flaky_checks.sql / 0009_mutation_checks.sql exactly (rules.md
-- §2.3):
--   * every table has id, created_at, updated_at (TEXT RFC-3339)
--   * TEXT UUID primary keys generated by the application layer
--   * every foreign key is indexed
--   * every column used in WHERE / ORDER BY is indexed
--   * snake_case names; parameterized SQL only at the call site
--
-- Status strings mirror the Rust `HealTestStatus` serde enum in
-- services/healing_service.rs (healed | still_failing | passed) and the Zod
-- literals in packages/shared/src/schemas/heal.schema.ts.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- heal_checks — one row per completed heal (a bounded run→regen→rerun loop).
--
-- `artifact_id` is the suite the heal *started from* (its stable identity for
-- the trend); `landed_version_id` is the regenerated version the heal settled
-- on (the healed attempt, or the best attempt by pass count) — a different
-- artifact id, kept as a plain reference, NOT a foreign key, so pruning an
-- intermediate version never deletes the historical check.
--
-- `landed_run_id` references the test_runs row of the landed attempt. The draft
-- doc called this `baseline_run_id` for parity with 0009, but heal has no
-- green-baseline concept — the meaningful run is the one it landed on, so the
-- honest name is used here. It is nullable + ON DELETE SET NULL so purging that
-- run (or it cascading away with the artifact's run history) never deletes the
-- historical check: heal history outlives any one run, exactly as flaky and
-- mutation history do. The artifact / project foreign keys still cascade, so
-- deleting the artifact removes its whole heal history.
--
-- `final_passing` / `final_total` are the landed attempt's pass ratio;
-- `attempts` is how many run→regen cycles the loop used.
-- ---------------------------------------------------------------------------
CREATE TABLE heal_checks (
    id                   TEXT PRIMARY KEY NOT NULL,
    artifact_id          TEXT NOT NULL,
    project_id           TEXT NOT NULL,
    landed_run_id        TEXT,
    landed_version_id    TEXT NOT NULL,
    attempts             INTEGER NOT NULL DEFAULT 0,
    healed_count         INTEGER NOT NULL DEFAULT 0,
    still_failing_count  INTEGER NOT NULL DEFAULT 0,
    final_passing        INTEGER NOT NULL DEFAULT 0,
    final_total          INTEGER NOT NULL DEFAULT 0,
    created_at           TEXT NOT NULL,
    updated_at           TEXT NOT NULL,
    FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (landed_run_id) REFERENCES test_runs(id) ON DELETE SET NULL
);

CREATE INDEX idx_heal_checks_artifact_id ON heal_checks(artifact_id);
CREATE INDEX idx_heal_checks_project_id ON heal_checks(project_id);
CREATE INDEX idx_heal_checks_created_at ON heal_checks(created_at);

-- ---------------------------------------------------------------------------
-- heal_check_tests — one row per test involved in the heal. `HealResult` only
-- carries the *failing* tests per attempt (not the always-passing ones), so a
-- persisted check re-renders the same per-test trail the live result view
-- derives: a test absent from the landed attempt's failures is `healed`
-- (it flipped to passing, `healed_at_attempt` = the attempt it first passed);
-- one still present is `still_failing` (a likely real source bug). The `passed`
-- literal exists for forward-compat (a future heal that records the full final
-- test list), and is accepted by the decode path though no writer emits it yet.
--
-- Identified by `name` (the test name), mirroring flaky_check_tests — the heal
-- verdict has no separate test id.
-- ---------------------------------------------------------------------------
CREATE TABLE heal_check_tests (
    id                    TEXT PRIMARY KEY NOT NULL,
    check_id              TEXT NOT NULL,
    name                  TEXT NOT NULL,
    -- healed | still_failing | passed
    status                TEXT NOT NULL,
    healed_at_attempt     INTEGER,
    last_failure_message  TEXT,
    created_at            TEXT NOT NULL,
    updated_at            TEXT NOT NULL,
    FOREIGN KEY (check_id) REFERENCES heal_checks(id) ON DELETE CASCADE
);

CREATE INDEX idx_heal_check_tests_check_id ON heal_check_tests(check_id);
